version: 2
updates:
  - package-ecosystem: npm
    directory: /action
    schedule:
      interval: daily
    groups:
      non-major:
        update-types:
          - minor
          - patch
  - package-ecosystem: npm
    directory: /cdk
    schedule:
      interval: daily
    groups:
      non-major:
        update-types:
          - minor
          - patch
  - package-ecosystem: npm
    directory: /ui
    schedule:
      interval: daily
    groups:
      non-major:
        update-types:
          - minor
          - patch
  - package-ecosystem: cargo
    directory: /api
    schedule:
      interval: daily
    groups:
      non-major:
        update-types:
          - minor
          - patch
