name: lcov
on:
  workflow_dispatch:

jobs:
  lcov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --json --output-path lcov.json
      - name: print coverage
        run: cat lcov.json | jq '.data[0].totals.lines.percent'